### ISSUE TITLE
NFT Support

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/lunaria#88]

**Comment by jubalm** [comment]
open for discussion

**Comment by MicahZoltu** [comment]
I am of the opinion that the NFT app should be separate from the ERC20 token management app.  We could have one link to the other but I think they are sufficiently different that we shouldn't bundle them.

It is also possible that we won't be able to provide the same level of privacy/anonymity protection with an NFT app as with a token management app, and I would hate to have to lose privacy protection on the token app just because supporting NFTs requires it.

**Comment by 0xjimmy** [comment]
Project created with basic functionality,
https://github.com/DarkFlorist/nft-wallet
